services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./src:/app/src
      - ./runs:/app/runs
      - ./figures:/app/figures
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "2222:22"
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  train:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./runs:/app/runs
      - ./figures:/app/figures
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: python src/main.py

volumes:
  data:
  runs:
  models:
  figures:
